steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}'
      - '--platform'
      - 'managed'
      - '--regions'
      - 'us-central1,us-east1,europe-west1'
      - '--zones'
      - 'us-central1-a,us-east1-b,europe-west1-b'
      
      # - '--region'
      # - '${_REGION}'
      - '--allow-unauthenticated' 
      - '--port'
      - '3000' 
    

options:
  # machineType: 'e2-standard-2'
  # diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: 'my-react-app'
  _REGION: 'asia-south2'